#!/usr/bin/env bash
# Function to get DNS information for a subdomain
print_domain_subdomain () {
    local subdomain="$1"
    local domain="$2"
    local result
    result=$(dig "$subdomain" | grep -A1 'ANSWER SECTION:' | awk -v sub="$subdomain" -v dom="$domain" 'NR==2 { sub(sub "\\.", dom "."); print "The subdomain " $1 " is a " $4 " record and points to " $5 }')
    echo "$result"
}

# Check if the correct number of arguments is provided
if [ "$#" -ne 1 ] && [ "$#" -ne 2 ]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

# Check if a subdomain is provided
if [ "$#" -eq 2 ]; then
    print_domain_subdomain "$2.$1" "$2"
else
    print_domain_subdomain "www.$1" "www"
    print_domain_subdomain "lb-01.$1" "lb-01"
    print_domain_subdomain "web-01.$1" "web-01"
    print_domain_subdomain "web-02.$1" "web-02"
fi
