#!/usr/bin/env bash
#Install nginx web server
#Nginx should be listening on port 80
# Bash script that configures a new Ubuntu machine 
#to respect above requirements
sudo apt-get update -y
sudo apt-get install nginx -y
sudo service nginx start
sudi ufw allow 'ngine HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -r 755 /var/www
echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
kill -s HUP "$(pgrep -x "nginx")"

