#!/usr/bin/env bash
#Install nginx web server
#Nginx should be listening on port 80
# Bash script that configures a new Ubuntu machine 
#to respect above requirements
sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'ngine HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
sudo service nginx restart
sudo nginx -s reload

