#!/usr/bin/env bash
# A bash script that installs nginx on an ubuntu machine.
# This scripts also configures the default webpage served to be "Hello World!"
# When request url matches /redirect_me, it redirects to my youtube channel.

sudo apt-get update -y

sudo apt-get install nginx -y

ufw allow 'Nginx HTTP'

echo "Hello World!" > /var/www/html/index.nginx-debian.html

sed -i "37i\\
    location /redirect_me {\\
        return 301 https://youtu.be/dQw4w9WgXcQ; \\
    }\\
" /etc/nginx/sites-available/default

service nginx restart
