#!/usr/bin/env bash
# Configure Nginx server with custom 404 page and redirection rule

# Update package index
sudo apt-get update -y

# Install Nginx
sudo apt-get install nginx -y

# Allow HTTP traffic through the firewall
ufw allow 'Nginx HTTP'

# Create index.html with "Hello World!"
echo "Hello World!" > /var/www/html/index.html

# Add redirection configuration to Nginx server block
sed -i "37i\\
    location /redirect_me {\\
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \\
    }\\
" /etc/nginx/sites-available/default

# Write "Ceci n'est pas une page" to the custom 404 error page file
echo "Ceci n'est pas une page" > /var/www/html/404error.html


# Add custom error handling configuration to Nginx server block
sed -i "37i\ \terror_page 404 /404error.html;\n\tlocation = /404error.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n" /etc/nginx/sites-available/default

# Restart Nginx service to apply changes
service nginx restart
