#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page
#The page must return an HTTP 404 error code
sudo apt-get update -y
sudo apt-get install nginx -y
sudo service nginx start
sudo ufw allow 'nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

