#!/usr/bin/env bash
# Update package lists and install nginx
sudo apt-get -y update
sudo apt-get -y install nginx

sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

sudo nginx -t
# Restart Nginx service
sudo service nginx restart

