#!/usr/bin/env bash
# Install HAProxy
sudo apt-get -y update
sudo apt-get install -y haproxy

# Configure HAProxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg > /dev/null
global
        log /dev/log    local0
        log /dev/log    local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
        stats timeout 30s
        user haproxy
        group haproxy
        daemon

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http

frontend http_front
        bind *:80
        mode http
        stats uri /haproxy?stats
        default_backend web_servers

backend web_servers
	balance roundrobin
	server 48058-web-01 100.25.34.19:80 check
	server 48058-web-02 100.27.2.0:80 check
EOF
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo haproxy -c -f /etc/haproxy/haproxy.cfg


# Restart and enable HAProxy service
sudo systemctl restart haproxy
sudo systemctl enable haproxy
