#!/usr/bin/env bash
#that script Accepts a string as an argument and displaye a message
#and ping 5 times

if [ $# -eq 0 ]; then
	echo "Usage: $0 {IP_ADDRESS}"
	exit 1
fi
ip_address=$1
ping -c 5 $ip_address
exit $?
