#!/usr/bin/env bash
#that script Accepts a string as an argument and displaye a message
#and ping 5 times

if [ $# -eq 1 ]; then
	echo "PING $1"
	ping -c 5 $1
else
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
