#!/bin/bash
#find out what’s keeping your Ubuntu container’s Nginx installation from listening on port 80
rm /etc/nginx/sites-enabled/default
#nginx listen on port 80
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#restart nginx
service nginx restart
