#!/usr/bin/env bash
#Using what you did for task #0, make your fix short and sweet.
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
