#!/usr/bin/env bash
# Bash script that: receiving a SIGTERM signal  receiving a SIGINT signal

pid_file="/var/run/myscript.pid"
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f "$pid_file"; exit' SIGQUIT

echo $$ > "$pid_file"
while true; do
	echo "To infinity and beyond"
	sleep 2
done
