#!/usr/bin/env bash

# Bash script to tell a story based on the /etc/passwd file

while IFS=":" read -r username _ uid gid info home shell; do
    gang_id=${gid:-"N/A"}
    passcode=${info:0:1}
    echo "The user $username is part of the $gang_id gang, lives in $home and rides $shell. $uid's place is protected by the passcode $passcode, more info about the user here: $info"
done < "/etc/passwd"
