#!/usr/bin/env bash
#script that gives you information about the school file

f_path="school"
if [ -e "$f_path" ]; then
	echo "school file exists"
	if [ -s "$f_path" ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "$f_path" ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
