#!/bin/bash
# Check if the script is run with exactly one argument
if [ "$#" -eq 1 ]; then
	uname="$1"
else
	uname="root"
    
fi

# Run the whoami command as the specified user
sudo -u "$uname" whoami

