#!/usr/bin/env bash
# Modify Nginx configuration to run as nginx user
sed -i 's/user\s*nginx;/user nginx;/g' /etc/nginx/nginx.conf

# Make sure Nginx is listening on all active IPs on port 8080
sed -i '/listen\s*80;/a\    listen 8080;' /etc/nginx/nginx.conf

chmod 644 /etc/nginx/nginx.conf

# Restart Nginx to apply changes
service nginx restart

