#!/usr/bin/env bash
# Modify Nginx configuration to run as nginx user
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i 's/listen\s*80;/listen *:8080;/g' /etc/nginx/sites-available/default
pkill apache2
service nginx restart

