#!/usr/bin/env bash
# Modify Nginx configuration to run as nginx user
sed -i 's/#user\s*nginx;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen\s*80;/listen *:8080;/g' /etc/nginx/sites-available/default
service nginx restart

